title = "Dan Bruder | Software Engineering Manager"
base_url = "https://danbruder.com/"
compile_sass = false
build_search_index = false

taxonomies = [
    {name = "tags"}, 
    {name = "category"}, 
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfDark"

[extra]
favicon = "static/my-face-new.jpg"
