[build]
publish = "public"
command = "yarn install && yarn run build && hugo --minify"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
HUGO_VERSION = "0.135.0"

